# Generated by Django 2.0.5 on 2018-05-13 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='updated_ap',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='updated_ap',
            new_name='updated_at',
        ),
    ]
